name: "Supinfo Build Scan"

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
  schedule:
    - cron: '42 11 * * 1'

permissions:
  actions: read
  contents: read
  security-events: write

env:
  JFrog_Project_Name: "demowei"
  JFrog_Mvn_Repo: "demowei-mvn-virtual"
  Build_name: "github-mvn-build"
  
jobs:
  security-java-demo:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup JFrog CLI
      uses: jfrog/setup-jfrog-cli@v4

      env:
        # JFrog Platform url
        JF_URL: ${{ secrets.JF_URL }}
        # JFrog Platform access token
        JF_ACCESS_TOKEN: ${{ secrets.JF_ACCESS_TOKEN }}

    - name: Build Maven Project
      run: |
        jf rt ping
        jf  mvnc --repo-resolve-releases=$JFrog_Mvn_Repo --repo-resolve-snapshots=$JFrog_Mvn_Repo --repo-deploy-releases=$JFrog_Mvn_Repo --repo-deploy-snapshots=$JFrog_Mvn_Repo
        jf  mvn clean install --build-name=$Build_name  --build-number=$GITHUB_RUN_NUMBER --project=$JFrog_Project_Name
       
    - name: Publish Build-Info to Supinfo Repo
      run: |
        jf rt bce $Build_name $GITHUB_RUN_NUMBER --project=$JFrog_Project_Name
        jf rt bag $Build_name $GITHUB_RUN_NUMBER --project=$JFrog_Project_Name
        jf rt bp $Build_name $GITHUB_RUN_NUMBER --project=$JFrog_Project_Name

  

